language: objective-c
osx_image: xcode8.3
xcode_workspace: WatchItLater.xcworkspace
xcode_scheme: WatchItLater
before_install:
- brew update
- brew outdated xctool || brew upgrade xctool
- gem install xcpretty
- gem update cocoapods
install:
- pod install --repo-update --project-directory=$TRAVIS_BUILD_DIR
before_script:
- mv 'App/Supporting Files/InstapaperConfiguration.defaults.plist' 'App/Supporting Files/InstapaperConfiguration.plist'
- xctool -workspace ${TRAVIS_XCODE_WORKSPACE} -scheme ${TRAVIS_XCODE_SCHEME} run-tests
script:
- set -o pipefail && xcodebuild -workspace ${TRAVIS_XCODE_WORKSPACE} -scheme ${TRAVIS_XCODE_SCHEME} -sdk appletvsimulator -configuration Release | xcpretty