name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
    - name: Setup Config
      run: mv 'App/Supporting Files/InstapaperConfiguration.defaults.plist' 'App/Supporting Files/InstapaperConfiguration.plist'
    - name: Build
      uses: sersoft-gmbh/xcodebuild-action@v2
      with:
        project: WatchItLater.xcworkspace
        scheme: WatchItLater
        configuration: debug
        sdk: appletvsimulator
        action: build
