name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: pod install --repo-update
    - name: Build
      uses: sersoft-gmbh/xcodebuild-action@v1.1
      with:
        workspace: WatchItLater.xcworkspace
        scheme: WatchItLater
        configuration: debug
        sdk: appletvsimulator
        action: build
